export const AIRLINE_CODE_MAP = {
  'AA': 'American Airlines',
  'DL': 'Delta Air Lines',
  'UA': 'United Airlines',
  'LH': 'Lufthansa',
  'AF': 'Air France',
  'KL': 'KLM',
  'BA': 'British Airways',
  'LX': 'SWISS',
  'OS': 'Austrian',
  'SK': 'SAS Scandinavian Airlines',
  'IB': 'Iberia',
  'AZ': 'ITA Airways',
  'EK': 'Emirates',
  'QR': 'Qatar Airways',
  'EY': 'Etihad Airways',
  'QF': 'Qantas',
  'SQ': 'Singapore Airlines',
  'NH': 'ANA All Nippon Airways',
  'JL': 'Japan Airlines',
  'TK': 'Turkish Airlines',
  'WN': 'Southwest Airlines',
  'AS': 'Alaska Airlines',
  'B6': 'JetBlue Airways',
  'AC': 'Air Canada',
  'NZ': 'Air New Zealand',
  'VA': 'Virgin Australia',
  'VS': 'Virgin Atlantic',
  'FR': 'Ryanair',
  'U2': 'easyJet',
  'VY': 'Vueling',
  'CX': 'Cathay Pacific',
  'CI': 'China Airlines',
  'MU': 'China Eastern',
  'CA': 'Air China',
  'HU': 'Hainan Airlines',
  'KE': 'Korean Air',
  'OZ': 'Asiana Airlines',
  'AY': 'Finnair',
  'SU': 'Aeroflot',
};
